[[Couenne]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd5a1d2f2f41b2aaa3a4ceafd976e7ee09e5643f"
libc = "glibc"
os = "linux"

    [[Couenne.download]]
    sha256 = "411d263db029adee3432337d289c8926da66d80d693b1a54e2f6f1d06f4b6ceb"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.aarch64-linux-gnu-cxx11.tar.gz"
[[Couenne]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd9dffc1d4862a2527dfa854b382f41c45b707ff"
libc = "musl"
os = "linux"

    [[Couenne.download]]
    sha256 = "7308b1fc47e0abab8a06b46ffbb1d87f509688627c416ac01f7725c0110ef548"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.aarch64-linux-musl-cxx11.tar.gz"
[[Couenne]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7245806633c63710c0ed8c0c7a61465ecf7751c5"
libc = "glibc"
os = "linux"

    [[Couenne.download]]
    sha256 = "22b16c63752704b21b55161ac045c4b9e8c9f197cc2f59d73fbf0210633dee8c"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Couenne]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b39b8e07da9defef8b880c30cb509ab22c423bb8"
libc = "musl"
os = "linux"

    [[Couenne.download]]
    sha256 = "7cfbaa4ca4774408f10e980ebf97065d94f51dc6aadb9516a267fea4a483a6c6"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Couenne]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e8fd34c21932e67bc2a9af7eba0bf32efefddd6"
libc = "glibc"
os = "linux"

    [[Couenne.download]]
    sha256 = "611ab0b60492cb27aa0003b039772e665a49cff16bd1874d04a9ff457f44f273"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.i686-linux-gnu-cxx11.tar.gz"
[[Couenne]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3c907e43feebaa1fd58dd81def995a17ca7237e"
libc = "musl"
os = "linux"

    [[Couenne.download]]
    sha256 = "f571a04004bc309ea5049e9a4023535c3e32cdc40d3f22ec7a87ffba99ef6134"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.i686-linux-musl-cxx11.tar.gz"
[[Couenne]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "958adcfc50336c3a6604fa3331bdadfb2d46ac9e"
os = "windows"

    [[Couenne.download]]
    sha256 = "dd6d123d13b6fdbb06747e62e21bd5c35fc8d8d188514856065e547dc9d10e3b"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.i686-w64-mingw32-cxx11.tar.gz"
[[Couenne]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3e15bf17b52ae65ddba389e057793c12e2dad20"
libc = "glibc"
os = "linux"

    [[Couenne.download]]
    sha256 = "3396308da4c8954f75b5dffe114d576a6a617661f652d2db998399f51de34740"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Couenne]]
arch = "x86_64"
git-tree-sha1 = "90f50c3d87455097d5ddb3bcd2a01507b405a79d"
os = "macos"

    [[Couenne.download]]
    sha256 = "6591e591ea39e3696913c35f6f04d6c913644b3654636b6e1f98f153635fe70a"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.x86_64-apple-darwin.tar.gz"
[[Couenne]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ae4d44351db189ef4ae81daca5706c4c4cf2288"
libc = "glibc"
os = "linux"

    [[Couenne.download]]
    sha256 = "9c0029acaada55c863d5c27164df123e20e0af4e4e01f7449091a73e5e3142f5"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.x86_64-linux-gnu-cxx11.tar.gz"
[[Couenne]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9ae15ecfd60819bde0eff0c6db8d72e5d8d3d36"
libc = "musl"
os = "linux"

    [[Couenne.download]]
    sha256 = "d428f9f991dce6b01e5831a65e5a929983cb117a6c2bf768add40bc7862c4937"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.x86_64-linux-musl-cxx11.tar.gz"
[[Couenne]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23b26cb5c5acbfeafc1866f8dd146b0e4c664bf1"
os = "windows"

    [[Couenne.download]]
    sha256 = "a327d857c816329be0a6caf6a5a18bdaf48d3818facf60cf74d480c6e7a98213"
    url = "https://github.com/JuliaBinaryWrappers/Couenne_jll.jl/releases/download/Couenne-v0.5.8+0/Couenne.v0.5.8.x86_64-w64-mingw32-cxx11.tar.gz"
