# Autogenerated wrapper script for Couenne_jll for x86_64-apple-darwin
export amplexe, libcouenne

using ASL_jll
using Bonmin_jll
using Cbc_jll
using Ipopt_jll
JLLWrappers.@generate_wrapper_header("Couenne")
JLLWrappers.@declare_library_product(libcouenne, "@rpath/libCouenne.1.dylib")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(ASL_jll, Bonmin_jll, Cbc_jll, Ipopt_jll)
    JLLWrappers.@init_library_product(
        libcouenne,
        "lib/libCouenne.1.4.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/couenne",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
